[package]
name = "tickHttp"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
reqwest = "0.12.9"
serde = { version = "1.0.215", features = ["derive"] }
serde_json="1.0"
tokio = { version = "1.41.1", features = ["full"] }
openssl = { version = "0.10", features = ["vendored"] }